### ISSUE TITLE
iOS: A cropped version of the screenshot is transmitted in screenshotCallback(String data)

### ISSUE THREAD

**Issue by kostasoft** [Super-Bin/flutter_screenshot_callback#4]
Hello!
The plugin works fine on android, but there is a problem on iOS:
When the screenshotCallback is triggered, it returns a kale path that is severely cropped compared to the screenshot itself.
Please fix this problem, otherwise it's great!

**Comment by omershafique-emblem** [comment]
Still this issue occurs to me, Any help?

**Comment by liranhao** [comment]
> Still this issue occurs to me, Any help?

update 0.0.8
